# Generated by Django 5.0.4 on 2024-04-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/speciality/')),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='media/course/')),
                ('active_users', models.CharField(max_length=10000)),
                ('price_type', models.CharField(choices=[('Dollars', '$'), ('Sum', 'sum')], max_length=10)),
                ('rating_users', models.CharField(max_length=5)),
                ('last_updated', models.DateField(auto_now=True)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/teacher/')),
                ('last_updated', models.DateField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.position')),
            ],
        ),
    ]
