# Generated by Django 5.0.4 on 2024-04-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating_users',
            field=models.CharField(default=0),
        ),
    ]
