# Generated by Django 5.0.4 on 2024-04-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_rating_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='speciality',
        ),
        migrations.AddField(
            model_name='course',
            name='speciality',
            field=models.ManyToManyField(to='course.speciality'),
        ),
    ]
