# Generated by Django 5.0.4 on 2024-04-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_course_speciality_course_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating_users',
            field=models.FloatField(default=0, null=True),
        ),
    ]
